### ISSUE TITLE
Change wiki link in readme

### ISSUE THREAD

**Issue by wernerglinka** [metalsmith/in-place#178]
In the Readme file the link to the wiki is wrong.

_If you want to wrap your source files in a common template, you can use [@metalsmith/layouts](https://github.com/metalsmith/metalsmith/layouts). For usage examples check out our [wiki](https://github.com/metalsmith/metalsmith/in-place/wiki). Feel free to contribute an example if anything is missing, or update the existing ones. For templating engine specific questions try..._

Is: https://github.com/metalsmith/metalsmith/in-place/wiki
Should be: https://github.com/metalsmith/in-place/wiki

**Comment by webketje** [comment]
There is no longer a wiki link in the readme and tbh the wiki is outdated so closing this
